TalanaRentCars/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import include

from django.conf.urls.static import static
from django.conf import settings

from . import views

from cars.views import CarListView

urlpatterns = [
    path('', CarListView.as_view(), name = 'index'),
    path('admin/', admin.site.urls),
    path('carros/',include('cars.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cars/urls.py
from django.urls import path

from . import views

app_name = 'cars'

urlpatterns = [
    path('<slug:slug>', views.CarDetailList.as_view(), name='car'), #id -> llave primaria o primary key

]

cars/models.py
# -*- coding: utf-8 -*-
import uuid

from django.db import models

from django.utils.text import slugify

from django.db.models.signals import pre_save

OPCIONES_CONSUMO = (
    ('bencina','BENCINA'),
    ('petrolero', 'PETROLERO'),
)
OPCIONES_MODELO_CAR = (
    ('microauto','MICROAUTO'),
    ('sedan','SEDAN'),
    ('suv','SUV'),
    ('todoterreno','TODOTERRENO'),
    ('coupe','COUPE'),
)
OPCIONES_TAMAÑO = (
    ('pequeño','PEQUEÑO'),
    ('mediano','MEDIANO'),
    ('grande','GRANDE'),
    ('extragrande','EXTRAGRANDE'),
)

# Create your models here.
class Car(models.Model):
    title = models.CharField(max_length=50, verbose_name='Nombre carro')
    marca_car = models.CharField(max_length=50, verbose_name='Marca carro')
    modelo_car = models.CharField(max_length=50, choices=OPCIONES_MODELO_CAR, default='sedan', verbose_name='Modelo carro')
    color_car = models.CharField(max_length=50, verbose_name='Color carro')
    patente = models.CharField(max_length=50, verbose_name='Patente', unique=True)
    num_puertas = models.IntegerField(verbose_name='Número de puertas',default='2')
    tipo_consumo = models.CharField(max_length=10, choices=OPCIONES_CONSUMO, default='bencina', verbose_name='Tipo de consumo')
    tamaño = models.CharField(max_length=15, choices=OPCIONES_TAMAÑO, default='mediano', verbose_name='Tamaño carro')
    image_car = models.ImageField(upload_to='cars/', null=False, blank=False, verbose_name='Foto del carro')
    slug = models.SlugField(null=False,blank=False,unique=True )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
      return self.patente
    
def set_slug(sender,instance, *args, **kwargs): #callback
   if instance.title and not instance.slug:
      slug = slugify(instance.title)

      while Car.objects.filter(slug=slug).exists():
         slug = slugify(
            '{}-{}'.format(instance.title, str(uuid.uuid4())[:8] )
         )

      instance.slug = slug
   

pre_save.connect(set_slug, sender=Car)

clients/models.py
from django.db import models

# Create your models here.
class Clients(models.Model):
    pass

TalanaRentCars/views.py
from django.shortcuts import render

from cars.models import Car

def index(request):
    cars = Car.objects.all().order_by('-id')

    return render(request, 'index.html', {
        'message':'Listado de carros',
        'title':'Carros',
        'cars':cars
    })

cars/views.py
from django.shortcuts import render

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView

from .models import Car

# Create your views here.
class CarListView(ListView):
    template_name = 'index.html'
    queryset = Car.objects.all().order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['message'] = 'Listado de carros'
        #print(context)
        return context

class CarDetailList(DetailView): #id -> pk
    model = Car
    template_name = 'cars/car.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #print(context)
        return context

clients/views.py
from django.shortcuts import render

# Create your views here.

cars/templates/cars/car.html
{% extends 'base.html' %}


{% block content %}
   
<div class="col-md-12">
    
    <div class="h1 text-center">{{ car.marca_car }} {{ car.title }}</div>

</div>

<div class="col-12">
    <div class="row no-gutters border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
        <div class="col-md-6 p-4 d-flex flex-column position-static">
            <div class="row">
                <div class="col">
                    <h4>Marca: <span class="text-success text-center">{{ car.marca_car }}</span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4>Modelo: <span class="text-success text-center">{{ car.modelo_car }}</span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4>Color: <span class="text-success text-center"><i class="fas fa-tint"></i> {{ car.color_car }}</span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4>Consumo: <span class="text-success text-center"><i class="fas fa-gas-pump"></i> {{ car.tipo_consumo }}</span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4>Tamaño: <span class="text-success text-center"><i class="fas fa-ruler-combined"></i> {{ car.tamaño }}</span></h4>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <h4>Puertas: <span class="text-success text-center"><i class="fas fa-car"></i> {{ car.num_puertas }}</span></h4>
                </div>
            </div>
        </div>
        <div class="col-md-6 d-none d-lg-block">
            {% if car.image_car %}
                <img src="{{ car.image_car.url }}" alt="{{ car.title }}" width="600">
            {% endif %}
        </div>
    </div>
</div> 
    
{% endblock content %}

cars/templates/cars/snippets/car.html
<!--Car-->
<div class="card h-100">

    {% if car.image_car %}
        <img src="{{car.image_car.url}}" alt="Imagen del carro" height="200">
    {% endif %}
    <div class="card-body">
        <h5 class="card-title">{{car.title}}</h5>
        <a href="{% url 'cars:car' car.slug %}" class="btn btn-primary">Ver más</a>
    </div>
</div>

cars/templates/cars/snippets/list.html
<div class="row">
    
    {% for object in object_list %}

        <div class="col-md-3">
            {% include 'cars/snippets/car.html' with car=object %}
        </div>

    {% endfor %}

</div>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Talana Rent A Car</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>

    {% include 'navbar.html' %}

    <div class="container">

        
        <div class="row mt-3">
            
            {% block content %}
                
            {% endblock content %}
                
        </div>
    </div>
    
</body>
<script src="https://kit.fontawesome.com/ac1fc99a56.js" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>

templates/index.html
{% extends 'base.html' %}


{% block content %}

<div class="col">
    <h4 class="text-center">{{ message }}</h4>
    {% include 'cars/snippets/list.html' %}
</div>

{% endblock content %}
    

templates/navbar.html
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a href="{% url 'index' %}" class="navbar-brand">Talana Rent A Car</a>

    <button type="button" name="button" class="navbar-toggler navbar-toggler-right" data-toggle="collapse" data-target="#navb">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div id="navb" class="navbar-collapse collapse hide">
        <ul class="nav navbar-nav ml-auto">

            

        </ul>
    </div>

</nav>